STRIPPED_RECEPTOR_FILE = "stripped_receptor.pdb"
LIGAND_FILE = "autobuilding_ligand.cif"
EVENT_MTZ_FILE = "event.mtz"
GRAFTED_MTZ_FILE = "grafted.mtz"
RHOFIT_DIR = "rhofit"
RHOFIT_EVENT_DIR = "rhofit_event"
RHOFIT_NORMAL_DIR = "rhofit_normal"
RHOFIT_RESULTS_FILE = "results.txt"
RHOFIT_RESULT_JSON_FILE = "result.json"
RHOFIT_NORMAL_RESULT_JSON_FILE = "result_normal.json"
RHOFIT_BEST_MODEL_FILE = "best.pdb"
RSCC_TABLE_FILE = "rscc_table.csv"

BUILD_DIR_PATTERN = "{pandda_name}_{dtag}_{event_idx}"